packages:
  - apps/*
  - packages/*

verifyDepsBeforeRun: false
allowBuilds:
  esbuild: true
  protobufjs: true
  unrs-resolver: true
onlyBuiltDependencies:
  - esbuild
  - protobufjs
  - unrs-resolver
trustPolicyExclude:
  - synckit
