packages:
  - apps/*
  - packages/*

verifyDepsBeforeRun: false
allowBuilds:
  cypress: true
  esbuild: true
  protobufjs: true
  unrs-resolver: true
onlyBuiltDependencies:
  - cypress
  - esbuild
  - protobufjs
  - unrs-resolver
trustPolicyExclude:
  - synckit@0.9.3
